# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-10-14 06:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='picture',
            name='pub_date',
        ),
        migrations.AlterField(
            model_name='location',
            name='name',
            field=models.CharField(max_length=60),
        ),
    ]
